using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace SecureServerBackup.WinForms
{
	partial class MainForm
	{
		private IContainer components;
		private MenuStrip mainMenuStrip;
		private StatusStrip mainStatusStrip;
		private ToolStripStatusLabel versionStatusLabel;
		private TabControl mainTabControl;
		private TabPage backupTabPage;
		private TabPage activityTabPage;
		private TabPage mountBackupsTabPage;
		private TabPage verifyTabPage;
		private TabPage restoreTabPage;
		private TabPage schedulesTabPage;
		private FlowLayoutPanel backupJobsPanel;
		private Panel activityTabPanel;
		private ListView mountBackupsListView;
		private ListView verifyBackupsListView;
		private TableLayoutPanel restoreRootLayout;
		private FlowLayoutPanel restoreActionsPanel;
		private ListView restoreBackupsListView;
		private Label emptyRestoreBackupsLabel;
		private Label restoreStatusLabel;
		private ListView schedulesListView;
		private Label emptyBackupJobsLabel;

		protected override void Dispose(bool disposing)
		{
			if (disposing && components != null)
			{
				components.Dispose();
			}

			base.Dispose(disposing);
		}

		private void InitializeComponent()
		{
			components = new Container();
			mainMenuStrip = new MenuStrip();
			mainStatusStrip = new StatusStrip();
			versionStatusLabel = new ToolStripStatusLabel();
			mainTabControl = new TabControl();
			backupTabPage = new TabPage();
			backupJobsPanel = new FlowLayoutPanel();
			emptyBackupJobsLabel = new Label();
			activityTabPage = new TabPage();
			activityTabPanel = new Panel();
			mountBackupsTabPage = new TabPage();
			mountBackupsListView = new ListView();
			verifyTabPage = new TabPage();
			verifyBackupsListView = new ListView();
			restoreTabPage = new TabPage();
			restoreRootLayout = new TableLayoutPanel();
			restoreActionsPanel = new FlowLayoutPanel();
			restoreBackupsListView = new ListView();
			emptyRestoreBackupsLabel = new Label();
			restoreStatusLabel = new Label();
			schedulesTabPage = new TabPage();
			schedulesListView = new ListView();
			mainStatusStrip.SuspendLayout();
			mainTabControl.SuspendLayout();
			backupTabPage.SuspendLayout();
			activityTabPage.SuspendLayout();
			mountBackupsTabPage.SuspendLayout();
			verifyTabPage.SuspendLayout();
			restoreTabPage.SuspendLayout();
			restoreRootLayout.SuspendLayout();
			schedulesTabPage.SuspendLayout();
			SuspendLayout();
			mainMenuStrip.ImageScalingSize = new Size(20, 20);
			mainMenuStrip.Location = new Point(0, 0);
			mainMenuStrip.Name = "mainMenuStrip";
			mainMenuStrip.Size = new Size(918, 28);
			mainMenuStrip.TabIndex = 0;
			mainMenuStrip.Text = "menuStrip1";
			mainStatusStrip.ImageScalingSize = new Size(20, 20);
			mainStatusStrip.Items.AddRange(new ToolStripItem[] { versionStatusLabel });
			mainStatusStrip.Location = new Point(0, 632);
			mainStatusStrip.Name = "mainStatusStrip";
			mainStatusStrip.SizingGrip = false;
			mainStatusStrip.Size = new Size(918, 26);
			mainStatusStrip.TabIndex = 1;
			versionStatusLabel.Name = "versionStatusLabel";
			versionStatusLabel.Size = new Size(129, 20);
			versionStatusLabel.Text = "Version: Loading...";
			mainTabControl.Controls.Add(backupTabPage);
			mainTabControl.Controls.Add(activityTabPage);
			mainTabControl.Controls.Add(mountBackupsTabPage);
			mainTabControl.Controls.Add(verifyTabPage);
			mainTabControl.Controls.Add(restoreTabPage);
			mainTabControl.Controls.Add(schedulesTabPage);
			mainTabControl.Dock = DockStyle.Fill;
			mainTabControl.DrawMode = TabDrawMode.OwnerDrawFixed;
			mainTabControl.ItemSize = new Size(110, 28);
			mainTabControl.Location = new Point(0, 28);
			mainTabControl.Name = "mainTabControl";
			mainTabControl.Padding = new Point(12, 4);
			mainTabControl.SelectedIndex = 0;
			mainTabControl.Size = new Size(918, 604);
			mainTabControl.SizeMode = TabSizeMode.Fixed;
			mainTabControl.TabIndex = 2;
			mainTabControl.DrawItem += MainTabControl_DrawItem;
			backupTabPage.Controls.Add(backupJobsPanel);
			backupTabPage.Location = new Point(4, 32);
			backupTabPage.Name = "backupTabPage";
			backupTabPage.Padding = new Padding(6);
			backupTabPage.Size = new Size(910, 568);
			backupTabPage.TabIndex = 0;
			backupTabPage.Text = "Backup";
			backupTabPage.UseVisualStyleBackColor = true;
			backupJobsPanel.AutoScroll = true;
			backupJobsPanel.BorderStyle = BorderStyle.FixedSingle;
			backupJobsPanel.Controls.Add(emptyBackupJobsLabel);
			backupJobsPanel.Dock = DockStyle.Fill;
			backupJobsPanel.FlowDirection = FlowDirection.TopDown;
			backupJobsPanel.Location = new Point(6, 6);
			backupJobsPanel.Name = "backupJobsPanel";
			backupJobsPanel.Padding = new Padding(12, 10, 12, 10);
			backupJobsPanel.Size = new Size(898, 556);
			backupJobsPanel.TabIndex = 0;
			backupJobsPanel.WrapContents = false;
			emptyBackupJobsLabel.AutoSize = true;
			emptyBackupJobsLabel.Location = new Point(25, 18);
			emptyBackupJobsLabel.Margin = new Padding(10, 8, 10, 8);
			emptyBackupJobsLabel.Name = "emptyBackupJobsLabel";
			emptyBackupJobsLabel.Size = new Size(223, 20);
			emptyBackupJobsLabel.TabIndex = 0;
			emptyBackupJobsLabel.Text = "No backup jobs have been created.";
			activityTabPage.Controls.Add(activityTabPanel);
			activityTabPage.Location = new Point(4, 32);
			activityTabPage.Name = "activityTabPage";
			activityTabPage.Padding = new Padding(6);
			activityTabPage.Size = new Size(910, 568);
			activityTabPage.TabIndex = 1;
			activityTabPage.Text = "Activity";
			activityTabPage.UseVisualStyleBackColor = true;
			activityTabPanel.Dock = DockStyle.Fill;
			activityTabPanel.Location = new Point(6, 6);
			activityTabPanel.Name = "activityTabPanel";
			activityTabPanel.Padding = new Padding(12);
			activityTabPanel.Size = new Size(898, 556);
			activityTabPanel.TabIndex = 0;
			mountBackupsTabPage.Controls.Add(mountBackupsListView);
			mountBackupsTabPage.Location = new Point(4, 32);
			mountBackupsTabPage.Name = "mountBackupsTabPage";
			mountBackupsTabPage.Padding = new Padding(6);
			mountBackupsTabPage.Size = new Size(910, 568);
			mountBackupsTabPage.TabIndex = 2;
			mountBackupsTabPage.Text = "Mount Backups";
			mountBackupsTabPage.UseVisualStyleBackColor = true;
			mountBackupsListView.Dock = DockStyle.Fill;
			mountBackupsListView.HideSelection = false;
			mountBackupsListView.Location = new Point(6, 6);
			mountBackupsListView.Name = "mountBackupsListView";
			mountBackupsListView.Size = new Size(898, 556);
			mountBackupsListView.TabIndex = 0;
			mountBackupsListView.UseCompatibleStateImageBehavior = false;
			verifyTabPage.Controls.Add(verifyBackupsListView);
			verifyTabPage.Location = new Point(4, 32);
			verifyTabPage.Name = "verifyTabPage";
			verifyTabPage.Padding = new Padding(6);
			verifyTabPage.Size = new Size(910, 568);
			verifyTabPage.TabIndex = 3;
			verifyTabPage.Text = "Verify";
			verifyTabPage.UseVisualStyleBackColor = true;
			verifyBackupsListView.Dock = DockStyle.Fill;
			verifyBackupsListView.HideSelection = false;
			verifyBackupsListView.Location = new Point(6, 6);
			verifyBackupsListView.Name = "verifyBackupsListView";
			verifyBackupsListView.Size = new Size(898, 556);
			verifyBackupsListView.TabIndex = 0;
			verifyBackupsListView.UseCompatibleStateImageBehavior = false;
			restoreTabPage.Controls.Add(restoreRootLayout);
			restoreTabPage.Location = new Point(4, 32);
			restoreTabPage.Name = "restoreTabPage";
			restoreTabPage.Padding = new Padding(6);
			restoreTabPage.Size = new Size(910, 568);
			restoreTabPage.TabIndex = 4;
			restoreTabPage.Text = "Restore";
			restoreTabPage.UseVisualStyleBackColor = true;
			restoreRootLayout.ColumnCount = 1;
			restoreRootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
			restoreRootLayout.Controls.Add(restoreActionsPanel, 0, 0);
			restoreRootLayout.Controls.Add(restoreBackupsListView, 0, 1);
			restoreRootLayout.Controls.Add(emptyRestoreBackupsLabel, 0, 2);
			restoreRootLayout.Controls.Add(restoreStatusLabel, 0, 3);
			restoreRootLayout.Dock = DockStyle.Fill;
			restoreRootLayout.Location = new Point(6, 6);
			restoreRootLayout.Name = "restoreRootLayout";
			restoreRootLayout.Padding = new Padding(10);
			restoreRootLayout.RowCount = 4;
			restoreRootLayout.RowStyles.Add(new RowStyle());
			restoreRootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
			restoreRootLayout.RowStyles.Add(new RowStyle());
			restoreRootLayout.RowStyles.Add(new RowStyle());
			restoreRootLayout.Size = new Size(898, 556);
			restoreRootLayout.TabIndex = 0;
			restoreActionsPanel.AutoSize = true;
			restoreActionsPanel.Location = new Point(13, 13);
			restoreActionsPanel.Margin = new Padding(0, 0, 0, 8);
			restoreActionsPanel.Name = "restoreActionsPanel";
			restoreActionsPanel.Size = new Size(0, 0);
			restoreActionsPanel.TabIndex = 0;
			restoreActionsPanel.WrapContents = true;
			restoreBackupsListView.Dock = DockStyle.Fill;
			restoreBackupsListView.HideSelection = false;
			restoreBackupsListView.Location = new Point(13, 21);
			restoreBackupsListView.Name = "restoreBackupsListView";
			restoreBackupsListView.Size = new Size(872, 469);
			restoreBackupsListView.TabIndex = 1;
			restoreBackupsListView.UseCompatibleStateImageBehavior = false;
			restoreBackupsListView.DoubleClick += RestoreBackupsListView_DoubleClick;
			emptyRestoreBackupsLabel.AutoSize = true;
			emptyRestoreBackupsLabel.Location = new Point(23, 498);
			emptyRestoreBackupsLabel.Margin = new Padding(10, 8, 10, 8);
			emptyRestoreBackupsLabel.Name = "emptyRestoreBackupsLabel";
			emptyRestoreBackupsLabel.Size = new Size(221, 20);
			emptyRestoreBackupsLabel.TabIndex = 2;
			emptyRestoreBackupsLabel.Text = "No restore backups are available.";
			restoreStatusLabel.AutoSize = true;
			restoreStatusLabel.Location = new Point(23, 526);
			restoreStatusLabel.Margin = new Padding(10, 0, 10, 8);
			restoreStatusLabel.Name = "restoreStatusLabel";
			restoreStatusLabel.Size = new Size(721, 20);
			restoreStatusLabel.TabIndex = 3;
			restoreStatusLabel.Text = "Select a backup to open the restore workflow. Restoring the boot/system drive requires the recovery environment.";
			schedulesTabPage.Controls.Add(schedulesListView);
			schedulesTabPage.Location = new Point(4, 32);
			schedulesTabPage.Name = "schedulesTabPage";
			schedulesTabPage.Padding = new Padding(6);
			schedulesTabPage.Size = new Size(910, 568);
			schedulesTabPage.TabIndex = 5;
			schedulesTabPage.Text = "Schedules";
			schedulesTabPage.UseVisualStyleBackColor = true;
			schedulesListView.Dock = DockStyle.Fill;
			schedulesListView.HideSelection = false;
			schedulesListView.Location = new Point(6, 6);
			schedulesListView.Name = "schedulesListView";
			schedulesListView.Size = new Size(898, 556);
			schedulesListView.TabIndex = 0;
			schedulesListView.UseCompatibleStateImageBehavior = false;
			AutoScaleDimensions = new SizeF(8F, 20F);
			AutoScaleMode = AutoScaleMode.Font;
			ClientSize = new Size(918, 658);
			Controls.Add(mainTabControl);
			Controls.Add(mainStatusStrip);
			Controls.Add(mainMenuStrip);
			MainMenuStrip = mainMenuStrip;
			MinimumSize = new Size(936, 671);
			Name = "MainForm";
			StartPosition = FormStartPosition.CenterScreen;
			Text = "Secure Server Backup";
			Load += MainForm_Load;
			Resize += MainForm_Resize;
			mainStatusStrip.ResumeLayout(false);
			mainStatusStrip.PerformLayout();
			mainTabControl.ResumeLayout(false);
			backupTabPage.ResumeLayout(false);
			backupTabPage.PerformLayout();
			activityTabPage.ResumeLayout(false);
			mountBackupsTabPage.ResumeLayout(false);
			verifyTabPage.ResumeLayout(false);
			restoreTabPage.ResumeLayout(false);
			restoreRootLayout.ResumeLayout(false);
			restoreRootLayout.PerformLayout();
			schedulesTabPage.ResumeLayout(false);
			ResumeLayout(false);
			PerformLayout();
		}
	}
}
